name: google_ml_kit_example
description: Demonstrates how to use the google_ml_kit plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.3
  image_picker: ^1.1.2
  camera: ^0.10.6
  path: ^1.9.0
  path_provider: ^2.1.4
  speech_to_text: ^7.0.0
  http: ^1.2.2
  flutter_tts: ^4.0.2
  cross_file: ^0.3.4+2
  flutter_gemini: ^2.0.5
  google_generative_ai: ^0.4.6

  google_mlkit_commons: any


  google_mlkit_object_detection:
    path: ../google_mlkit_object_detection
  permission_handler: ^11.3.1


dependency_overrides:
  google_mlkit_commons:
    path: ../google_mlkit_commons

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
    - assets/images/
